spring:
  application:
    name: eureka-server


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTineInMsWhenSyncEmpty: 0

server:
  port: 8302

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301
    login-service:
      path: /login-service/**
      url: http://localhost:8299


